- name: install apt_repository dependencies
  apt:
    name: "{{ item }}"
  loop:
    - "{{ haproxy_ppa.dependencies }}"
  tags:
    - haproxy
    - haproxy-install

- name: add ppa
  apt_repository:
    repo: "{{ haproxy_ppa.address }}"
  tags:
    - haproxy
    - haproxy-install

- name: install haproxy
  apt:
    name: haproxy={{ haproxy_version }}
    update_cache: yes
  tags:
    - haproxy
    - haproxy-install

- name: template haproxy config
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy
  tags:
    - haproxy
    - haproxy-install
    - haproxy-configure
